// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdixretgriomlqpldrnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkaXhyZXRncmlvbWxxcGxkcm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NDY0NjAsImV4cCI6MjA1MTQyMjQ2MH0.w1SsG_DoxqhUPkBIcYstOk5BM8mEAhZZRhph_8Ov9Y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);